# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  VALOR_VARIAVEL: ${{secrets.VARIAVEL}}
  VALOR_VARIAVEL_2: ${{secrets.VARIAVEL_2}}
  VALOR_VARIAVEL_3: valor3
  
    
jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['1.18', '1.17', '>=1.18']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.node_version }}

    - name: Build-db
      run: docker-compose build 

    - name: Create-db
      run: docker-compose up -d 

    - name: Test
      run: |
        echo "Variavel no secrets valor $VALOR_VARIAVEL , $VALOR_VARIAVEL_2,  $VALOR_VARIAVEL_3 " 
        go test -v main_test.go
        

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go

